name: Build Kernel

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y binutils gcc bison flex libssl-dev libncurses-dev bc git curl wget ccache

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/luxun4/android_kernel_xiaomi_sm8550
          kernel-dir: sm8550
          kernel-branch: lineage-21
          config: gki_defconfig
          arch: arm64

          # 关键：使用 AOSP clang，避免和 glibc 不兼容
          aosp-clang: true

          # 不使用 proton-clang
          other-clang-url: ""
          other-clang-branch: ""

          # KSU 和其他选项按你需要
          ksu: true
          ksu-version: main

          disable-lto: true
          anykernel3: true

          # 不需要设置 extra-cmd，避免污染
          extra-cmd: ""