name: Build Kernel

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y binutils gcc bison flex libssl-dev libncurses-dev bc git curl wget ccache

      - name: Clone Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git $HOME/toolchains/proton-clang

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        env:
          LD: ${{ env.HOME }}/toolchains/proton-clang/bin/ld.lld
          HOSTLD: ${{ env.HOME }}/toolchains/proton-clang/bin/ld.lld
          CC: clang
          HOSTCC: clang
        with:
          kernel-url: https://github.com/luxun4/android_kernel_xiaomi_sm8550
          kernel-dir: sm8550
          kernel-branch: lineage-21
          config: gki_defconfig
          arch: arm64

          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang.git
          other-clang-branch: master

          ksu: true
          ksu-version: main

          disable-lto: true
          anykernel3: true

          extra-cmd: ""